import Head from 'next/head';
import styles from '../../styles/mostrarLivro.module.css';
import api from '../api/api';
import CardLivro from '../../components/Card/Book';
import Header from '../../components/Header';
import Footer from '../../components/Footer';
import { GetServerSideProps } from 'next';

type LivroType = {
  livros: [
    {
      id: number;
      titulo: string;
      autor: number;
      editora: string;
      data_publicacao: string;
      preco: string;
    }
  ];
};

//Função pega os dados de todos os livros do banco
export const getServerSideProps: GetServerSideProps =
  async () => {
    const response = await api.get('/livros');
    const livros = response.data;
    return {
      props: {
        livros
      }
    };
  };

export default function Home({ livros }: LivroType) {
  return (
    <div className={styles.container}>
      <Head>
        <title>ProMatch</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={styles.autor}>
        {livros.map(
          ({
            autor,
            data_publicacao,
            editora,
            id,
            preco,
            titulo
          }) => {
            return (
              <div key={id}>
                <CardLivro
                  id={id}
                  titulo={titulo}
                  autor={autor}
                  editora={editora}
                  data={data_publicacao}
                  preco={preco}
                />
              </div>
            );
          }
        )}
      </div>
      <Footer />
    </div>
  );
}
