import Head from 'next/head'
import styles from '../../styles/mostrarLivro.module.css'
import api from '../api/api'
import CardLivro from '../../components/CardLivro'
import Header from '../../components/Header'
import Footer from '../../components/Footer'
import Logo from '../../components/Logo'

//Função pega os dados de todos os livros do banco
export async function getServerSideProps() {
    const response = await api.get("/livros")
    const livros = response.data
    return {
        props: {
            livros
        }
    }
}

export default function Home({ livros }) {

    return (
        <div className={styles.container}>
            <Head>
                <title>ProMatch</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Logo />
            <Header />
            <div className={styles.autor}>
                {livros.map(livro => {
                    return (
                        <div key={livro.id}>
                            <CardLivro id={livro.id} titulo={livro.titulo} autor={livro.autor} editora={livro.editora} data={livro.data_publicacao} preco={livro.preco} />
                        </div>
                    )
                })}

            </div>
            <Footer />
        </div>
    )
}
