import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Footer from '/components/Footer'
import Header from '../components/Header'
import Logo from '../components/Logo'
import CardAutor from '../components/CardAutor'
import api from './api/api'

//Função pega os dados de todos os autores
export async function getServerSideProps() {
  const response = await api.get("/")
  const autores = response.data
  return {
    props: {
      autores
    }
  }
}
export default function Home({ autores }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>ProMatch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Logo />
      <div className={styles.autor}>
        {autores.map(autor => {
          return (
            <div key={autor.id}>
              <CardAutor id={autor.id} nome={autor.nome} sobrenome={autor.sobrenome} data={autor.data_nascimento} />
            </div>
          )
        })
        }
      </div>
      <Footer />
    </div>
  )
}
