import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Footer from '../components/Footer';
import Header from '../components/Header';
import CardAutor from '../components/CardAutor';
import api from './api/api';
import { GetServerSideProps } from 'next';

type AutorType = {
  autores: [
    {
      id?: number;
      nome: string;
      sobrenome: string;
      data_nascimento: string;
    }
  ];
};

//Função pega os dados de todos os autores
export const getServerSideProps: GetServerSideProps =
  async () => {
    const response = await api.get('/autor');
    const autores = response.data;
    return {
      props: {
        autores
      }
    };
  };
export default function Home({ autores }: AutorType) {
  return (
    <div className={styles.container}>
      <Head>
        <title>ProMatch</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={styles.autor}>
        {autores.map(
          ({ data_nascimento, nome, sobrenome, id }) => {
            return (
              <div key={id}>
                <CardAutor
                  id={id}
                  nome={nome}
                  sobrenome={sobrenome}
                  data={data_nascimento}
                />
              </div>
            );
          }
        )}
      </div>
      <Footer />
    </div>
  );
}
