import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Footer from '/components/Footer'
import Header from '../components/Header'
import TelaInicial from '../components/telaInicial'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ProMatch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Image
        src="/images/tela_inicial.jpg"
        alt="Estudantes"
        width={1920}
        height={1920}
      />
      <TelaInicial/>
      <Footer />
    </div>
  )
}
